# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [1]:
# required imports
import numpy as np
import fnmatch
import os
import re


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [2]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [3]:
#Your code starts here   
directory_path = r'C:\A fifth Semester Notes\Machine Learning\Assignmnet 2 - IRS\Assignmnet 2 - IRS\nfiles'
file_count = 0

for f in os.listdir(directory_path):
    if f.endswith(".txt"):
        file_count += 1
        file_path = os.path.join(directory_path, f)
        
        with open(file_path, 'r') as file:
            content = file.read()
            
            files_dict[f] = {
                'count': file_count,
                'content': content
            }
            
print(files_dict)


#Your code ends here       

{'t1.txt': {'count': 1, 'content': 'I am student\n'}, 't2.txt': {'count': 2, 'content': 'I am going there'}, 't3.txt': {'count': 3, 'content': 'He is interesting'}}


Displaying the count of files.

In [4]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [5]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'t1.txt': {'count': 1, 'content': 'I am student\n'}, 't2.txt': {'count': 2, 'content': 'I am going there'}, 't3.txt': {'count': 3, 'content': 'He is interesting'}}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [6]:
#Your code starts here    
for f in os.listdir(directory_path):
    if f.endswith(".txt"):
        file_path = os.path.join(directory_path, f)
        
        with open(file_path, 'r') as file:
            content = file.read()
            
            words = [word.lower() for word in content.split() if word.isalpha()]

            unique_word_set.update(set(words))

print(f'Unique Words in every file\n{unique_word_set}')
#Your code ends here


Unique Words in every file
{'going', 'is', 'he', 'there', 'i', 'interesting', 'student', 'am'}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [7]:
#Your code starts here    
term_doc_matrix = []


term_doc_matrix = [[0] * len(unique_word_set) for _ in range(len(os.listdir(directory_path)))]

print(term_doc_matrix)

unique_words_dict = {word: index for index, word in enumerate(unique_word_set)}

print(" Dictionary of Unique words:")
print(unique_words_dict)
import os

files_dict = {file: index for index, file in enumerate(os.listdir(directory_path)) if file.endswith(".txt")}

print("Dictionary of files:")
print(files_dict)

#Your code ends here


[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]
 Dictionary of Unique words:
{'going': 0, 'is': 1, 'he': 2, 'there': 3, 'i': 4, 'interesting': 5, 'student': 6, 'am': 7}
Dictionary of files:
{'t1.txt': 0, 't2.txt': 1, 't3.txt': 2}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [8]:
#Your code starts here    

for file_index, filename in enumerate(os.listdir(directory_path)):
    if filename.endswith(".txt"):
        file_path = os.path.join(directory_path, filename)
        
        with open(file_path, 'r') as file:
            content = file.read()
            
            words = [word.lower() for word in content.split() if word.isalpha()]

            
            for word in words:
                if word in unique_word_set:
                    term_doc_matrix[file_index][unique_words_dict[word]] = 1
print(unique_words_dict)
print('\n')
#print(term_doc_matrix)
for row in term_doc_matrix:
    print(row)
    

#Your code ends here

{'going': 0, 'is': 1, 'he': 2, 'there': 3, 'i': 4, 'interesting': 5, 'student': 6, 'am': 7}


[0, 0, 0, 0, 1, 0, 1, 1]
[1, 0, 0, 1, 1, 0, 0, 1]
[0, 1, 1, 0, 0, 1, 0, 0]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [9]:
#Your code starts here    



import numpy as np

user_query_vector = np.zeros((len(unique_word_set), 1))

print("Empty User Query Vector:")
print(user_query_vector)

#Your code ends here

Empty User Query Vector:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [10]:
query = input("\nWrite something for searching:  ")
print("Query is:", query)


Write something for searching:  he is fascinating
Query is: he is fascinating


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [11]:
synonym_file_path = r"C:\A fifth Semester Notes\Machine Learning\Assignmnet 2 - IRS\Assignmnet 2 - IRS\files\synonyms.txt"
synonyms_dict = {} 
#your code starts here
with open(synonym_file_path, 'r') as sf:
    for i in sf:
        parts = i.strip().split(':')
        k = parts[0].strip().lower()
        synonyms = [s.strip().lower() for s in parts[1].split(',')]
        synonyms_dict[k] = synonyms


#your code ends here

print("\nSynonyms Dictionary\n")
synonyms_dict


Synonyms Dictionary



{'write': ['compose', 'draft', 'author', 'create'],
 'file': ['document', 'record', 'dossier', 'report'],
 'example': ['illustration', 'instance', 'sample', 'demonstration'],
 'query': ['question', 'inquiry', 'search', 'request'],
 'synonym': ['equivalent', 'substitute', 'alternate', 'replacement'],
 'retrieve': ['fetch', 'recover', 'obtain', 'bring back'],
 'system': ['framework', 'structure', 'organization', 'arrangement'],
 'search': ['seek', 'look for', 'explore', 'examine'],
 'lost': ['misplaced', 'missing', 'forgotten', 'mislaid'],
 'pen': ['write', 'ink', 'ballpoint', 'fountain'],
 'paper': ['document', 'sheet', 'form', 'letter'],
 'book': ['novel', 'volume', 'publication', 'tome'],
 'read': ['peruse', 'scan', 'study', 'look at'],
 'interesting': ['fascinating', 'engaging', 'intriguing', 'absorbing'],
 'computer': ['machine', 'device', 'processor', 'laptop'],
 'software': ['program', 'application', 'app', 'platform']}

### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [12]:
expanded_query = []
# Write code to expand the query using synonyms
#your code starts here

expanded_query = []

# your code starts here
for word in query.split():
    word = word.lower()
    expanded_query.append(word)
    if word in synonyms_dict:
        expanded_query.extend(synonyms_dict[word])
    else:
        for key, values in synonyms_dict.items():
            if word in values:
                expanded_query.extend([key] + values)
# your code ends here


print("Expanded Query")
print(expanded_query)

Expanded Query
['he', 'is', 'fascinating', 'interesting', 'fascinating', 'engaging', 'intriguing', 'absorbing']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [13]:
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary


In [14]:
#Your code starts here    

query_words = [word.lower() for word in expanded_query if word.isalpha()]

for word in query_words:
    if word in unique_word_set:
        user_query_vector[list(unique_word_set).index(word)] += 1
# Display the user query vector
print("\nUser Query Vector:")
print(user_query_vector)
#Your code ends here


User Query Vector:
[[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [15]:
#Your code starts here  
resultant_vector = np.dot(term_doc_matrix, user_query_vector)

print("\nResult:")
print(resultant_vector)

max_index = np.argmax(resultant_vector)

print("max_index", max_index)
max_value = np.max(resultant_vector)
print("Max Value :", max_value)
#Your code ends here





Result:
[[0.]
 [0.]
 [3.]]
max_index 2
Max Value : 3.0


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [16]:
#Your code starts here    

max_index = np.argmax(resultant_vector)
max_file_name = list(files_dict.keys())[max_index]

max_file_path = os.path.join(directory_path, max_file_name)
with open(max_file_path, 'r') as m:
    max_file_contents = m.read()
    print(f"\nContents of File '{max_file_name}':\n")
    print(max_file_contents)

#Your code ends here


Contents of File 't3.txt':

He is interesting


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.